config/routes.rb
BtcProfitCalc::Application.routes.draw do
  root :to => 'purchases#index'

  get '/ticker', controller: :application, action: :ticker
  get '/update', controller: :purchases, action: :update

  resources :purchases
  resources :denominations

end

app/models/bitcoin.rb
class Bitcoin
  attr_reader :denomination, :value

  def initialize(value = 0.0, denomination = Denomination.btc)
    @value = value
    @denomination = denomination
  end

  def is_usd?
    denomination == Denomination.usd
  end

  def to_s
    "#{"%5.4f" % as_denomination} #{denomination.symbol}"
  end

  def as_denomination
    value / denomination.value
  end

  def to_usd
    value * Denomination.usd.value
  end
end

app/models/denomination.rb
class Denomination < ActiveRecord::Base

  attr_accessible :name, :symbol, :value

  BTC   = 1
  MBTC  = 2
  UBTC  = 3
  USD   = 4

  def value
    return self[:value] unless id == USD
    self.class.bitstamp
  end

  class << self
    
    def bitstamp
      Rails.cache.fetch("bitstamp_cache", expires_in: 5.seconds) do
        Bitstamp::Ticker.last.to_f
      end
    end

    def method_missing(method, *args)
      type = "Denomination::#{method.to_s.upcase}"
      if defined?(type)
        find(type.constantize)
      else
        super
      end
    end
  end

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :amount, :date, :paid

  def bitcoin
    @bitcoin ||= Bitcoin.new(amount)
  end

  def profit
    bitcoin.to_usd - paid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def ticker
    render partial: 'welcome/ticker'
  end

  def update
    @purchases = Purchase.all
    @current_btc = Bitcoin.new(@purchases.to_a.sum(&:amount))

    render partial: 'purchases/table'
  end

end

app/controllers/denominations_controller.rb
class DenominationsController < ApplicationController
  # GET /denominations
  # GET /denominations.json
  def index
    @denominations = Denomination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @denominations }
    end
  end

  # GET /denominations/1
  # GET /denominations/1.json
  def show
    @denomination = Denomination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @denomination }
    end
  end

  # GET /denominations/new
  # GET /denominations/new.json
  def new
    @denomination = Denomination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @denomination }
    end
  end

  # GET /denominations/1/edit
  def edit
    @denomination = Denomination.find(params[:id])
  end

  # POST /denominations
  # POST /denominations.json
  def create
    @denomination = Denomination.new(params[:denomination])

    respond_to do |format|
      if @denomination.save
        format.html { redirect_to @denomination, notice: 'Denomination was successfully created.' }
        format.json { render json: @denomination, status: :created, location: @denomination }
      else
        format.html { render action: "new" }
        format.json { render json: @denomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /denominations/1
  # PUT /denominations/1.json
  def update
    @denomination = Denomination.find(params[:id])

    respond_to do |format|
      if @denomination.update_attributes(params[:denomination])
        format.html { redirect_to @denomination, notice: 'Denomination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @denomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denominations/1
  # DELETE /denominations/1.json
  def destroy
    @denomination = Denomination.find(params[:id])
    @denomination.destroy

    respond_to do |format|
      format.html { redirect_to denominations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
    @current_btc = Bitcoin.new(@purchases.to_a.sum(&:amount))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchases }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new
    @purchase = Purchase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/1/edit
  def edit
    @purchase = Purchase.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(params[:purchase])

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to root_url, notice: 'Purchase was successfully created.' }
        format.json { render json: @purchase, status: :created, location: @purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchases/1
  # PUT /purchases/1.json
  def update
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      if @purchase.update_attributes(params[:purchase])
        format.html { redirect_to root_url, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@bitcoin = Bitcoin.new(0.061)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_readable_timestamp(date_time = DateTime.now)
    date_time.strftime '%m/%d/%Y %H:%M:%S'
  end

  def human_readable_time(date_time = DateTime.now)
    date_time.strftime '%H:%M:%S' 
  end

  def human_readable_date(date_time = DateTime.now)
    date_time.strftime '%m/%d/%Y'
  end

  def from_string(string)
    DateTime.parse string
  end
end

app/helpers/denominations_helper.rb
module DenominationsHelper
  def as_mbtc(bitcoin)
    denomination = Denomination.mbtc
    "#{"%5.6f" % (value / denomination.value)} #{denomination.symbol}"
  end

  def as_usd(value)
    "$#{"%5.2f" % value}"
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
  def roi(profit, paid)
    '%2.2f' % ((profit / paid) * 100)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/denominations/_form.html.erb
<%= form_for @denomination, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :symbol, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :symbol, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                denominations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/denominations/edit.html.erb
<%- model_class = Denomination -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/denominations/index.html.erb
<%- model_class = Denomination -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:symbol) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @denominations.each do |denomination| %>
      <tr>
        <td><%= link_to denomination.id, denomination_path(denomination) %></td>
        <td><%= denomination.symbol %></td>
        <td><%= denomination.name %></td>
        <td><%= denomination.value %></td>
        <td><%=l denomination.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_denomination_path(denomination), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      denomination_path(denomination),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_denomination_path,
            :class => 'btn btn-primary' %>

app/views/denominations/new.html.erb
<%- model_class = Denomination -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/denominations/show.html.erb
<%- model_class = Denomination -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:symbol) %>:</strong></dt>
  <dd><%= @denomination.symbol %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @denomination.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @denomination.value %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              denominations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_denomination_path(@denomination), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              denomination_path(@denomination),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bitcoin Profit Tracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">

      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Bitcoin Profit Tracker</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li id='ticker' class="pull-right"><%= render 'welcome/ticker' %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


    
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span8 offset2">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <small></small>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_for @purchase, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :paid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :paid, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                purchases_path, :class => 'btn' %>
  </div>
<% end %>

app/views/purchases/_table.html.erb
<%
  total_paid = @purchases.to_a.sum(&:paid) 
  total_profit = @purchases.to_a.sum(&:profit) 
%>
  <thead>
    <tr>
      <th>Purchase Date</th>
      <th>Amount</th>
      <th>Paid</th>
      <th>Current</th>
      <th>Profit</th>
      <th>ROI</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= human_readable_date from_string(purchase.date) %></td>
        <td><%= purchase.bitcoin %></td>
        <td><%= as_usd purchase.paid %></td>
        <td><%= as_usd purchase.bitcoin.to_usd %></td>
        <td><%= as_usd purchase.profit %></td>
        <td><%= "#{roi purchase.profit, purchase.paid}%" %></td>
        <td>
          <%= link_to 'Details',
                      purchase_path(purchase), :class => 'btn btn-mini' %>
      </tr>
    <% end %>
    <tr class='totals'>
      <td>Totals</td>
      <td><%= @current_btc %></td>
      <td><%= as_usd total_paid %></td>
      <td><%= as_usd @current_btc.to_usd %></td>
      <td><%= as_usd total_profit %></td>
      <td><%= "#{roi total_profit, total_paid}%" %></td>
      <td></td>
    </tr>
  </tbody>

app/views/purchases/edit.html.erb
<%- model_class = Purchase -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/purchases/index.html.erb
<%- model_class = Purchase -%>
<%= link_to "Add Purchase",
            new_purchase_path,
            :class => 'btn btn-primary pull-right' %>
<table class="table table-striped" id='purchases'>
  <%= render partial: 'table' %>
</table>

app/views/purchases/new.html.erb
<%- model_class = Purchase -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/purchases/show.html.erb
<%- model_class = Purchase -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @purchase.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @purchase.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:paid) %>:</strong></dt>
  <dd><%= @purchase.paid %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              purchases_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_purchase_path(@purchase), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              purchase_path(@purchase),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/_ticker.html.erb
<%= link_to  "Bitstamp: #{as_usd(Bitcoin.new(1).to_usd)}/BTC", '', title: "Price cached for up to 15 seconds."  %>

app/views/welcome/index.html.erb
<p title='rounded'><%= " #{@bitcoin} / #{@bitcoin.as_usd}" %></p>